### ISSUE TITLE
Initiate connection to neo4j in Vuejs main.js script

### ISSUE THREAD

**Issue by Wenzel** [adam-cowley/vue-neo4j#1]
Hi,

In your README you are building the connection in one of the components, with hardcoded data.

Is there a way to initiate this connection directly in `main.js`, right after `Vue.use(VueNeo4j)` ?
~~~Javascript
Vue.use(VueNeo4j)

// ?
$neo4j.connect('bolt', 'localhost', 7687, 'user', 'password')
~~~

This way i would just have to use `const session = this.$neo4j.getSession()` in my methods to get an instance of `neo4j`  driver.

Is it possible ?
I'm not very familiar with VueJS, nor Javascript in general.

Thanks !

**Comment by adam-cowley** [comment]
You can't do this at the moment - the quickest way would be to connect in the `created()` method in your App.vue component.  
```
export default {
  name: 'App',
  // ...
  created() {
    this.$neo4j.connect('bolt', 'localhost', 7687, 'user', 'password')
  }
}
```
Then you could use `this.$neo4j.getSession()` elsewhere in the application
