### ISSUE TITLE
Property or method "protocol" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by a1oleg** [adam-cowley/vue-neo4j#10]
Property or method "protocol, host, port, username, password" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property

**Comment by adam-cowley** [comment]
Can you provide a code example to replicate this issue please?

**Comment by a1oleg** [comment]
https://github.com/a1oleg/vue4j/blob/master/src/components/HelloWorld.vue

Property or method "connect" is not defined on the instance but referenced during render....
"TypeError: _vm.connect is not a function"

**Comment by adam-cowley** [comment]
How did you create this project?  It doesn't look like the data function is being called on the `HelloWorld` component

**Comment by a1oleg** [comment]
I created Hello world via vue cli and then copied your code to HelloWorld.vue  and 
`import VueNeo4j from 'vue-neo4j'`
`Vue.use(VueNeo4j)`
to main.js

**Comment by adam-cowley** [comment]
Something is stopping vue from working somewhere but I can't see where.  This seems to work for me though.  Maybe try copying the code method by method to see where it breaks?

```
<template>
  <div class="hello">
    <pre>{{protocol}}://{{host}}:{{port}}</pre>
    <pre>{{username}}:{{password}}</pre>

    <input v-model="protocol" />
    <input v-model="host" />
    <input v-model="port" />
    <input v-model="username" />
    <input v-model="password" />
    <button @click="connect()">Connect</button>
  </div>
</template>

<script>
/* eslint-disable */
export default {
  name: "MyComponent",
  data() {
    return {
      protocol: "bolt",
      host: "localhost",
      port: 7687,
      username: "neo4j",
      password: "trustno1",
    };
  },
  methods: {
    connect() {
      return this.$neo4j
        .connect(
          this.protocol,
          this.host,
          this.port,
          this.username,
          this.password
        )
        .then((driver) => {
          // Update the context of your app
          console.log(driver);
        });
    },
    driver() {
      // Get a driver instance
      return this.$neo4j.getDriver();
    },
    testQuery() {
      // Get a session from the driver
      const session = this.$neo4j.getSession();

      // Or you can just call this.$neo4j.run(cypher, params)
      session
        .run("MATCH (n) RETURN count(n) AS count")
        .then((res) => {
          console.log(res.records[0].get("count"));
        })
        .then(() => {
          session.close();
        });
    },
  },
};
</script>
```

**Comment by a1oleg** [comment]
after some dance with webpack it working. tx
