### ISSUE TITLE
Cannot read property 'parseComponent' of undefined

### ISSUE THREAD

**Issue by a1oleg** [adam-cowley/vue-neo4j#11]
error  in ./node_modules/vue-neo4j/src/components/DatabaseInformation.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (C:\Users\a1ole\Documents\GitHub\vue4j\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (C:\Users\a1ole\Documents\GitHub\vue4j\node_modules\vue-loader\lib\index.js:67:22)

 @ ./node_modules/vue-neo4j/src/index.js 17:0-76 172:22-46 172:53-77
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.5:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/vue-neo4j/src/components/Connect.vue

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (C:\Users\a1ole\Documents\GitHub\vue4j\node_modules\@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (C:\Users\a1ole\Documents\GitHub\vue4j\node_modules\vue-loader\lib\index.js:67:22)

 @ ./node_modules/vue-neo4j/src/index.js 16:0-52 171:22-34 171:41-53
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.5:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by adam-cowley** [comment]
Do you have any more information?  Which version of Vue are you using? Have you got a repo that replicates this issue?

**Comment by a1oleg** [comment]
vue@2.6.12
https://github.com/a1oleg/vue4j

**Comment by adam-cowley** [comment]
It looks like a version mis-match in the vue dependencies and not strictly anything to do with vue-neo4j.  I got it to run by removing the following line from package.json and running `npm ci` 
```
"vue-template-compiler": "^2.6.11"
```
