### ISSUE TITLE
Unable to connect to Neo4j, net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by lauri108** [adam-cowley/vue-neo4j#2]
Hi @adam-cowley, 

I've implemented the example code from this repo, and seem to establish a database connection, but am not able to execute queries against an existing graph.

I've set up a database on the Neo4j desktop, and am able to connect to it using the desktop browser just fine. After running connect() in vuejs, and getting this.$neo4j.getDriver(), I get this:

`ConnectionStatus: { "_url": "localhost:7687", "_userAgent": "neo4j-javascript/1.5.1", "_openSessions": {}, "_sessionIdGenerator": 0, "_token": { "scheme": "basic", "principal": "neo4j", "credentials": "xxxxxxxxx" }, "_config": { "encrypted": true, "maxConnectionLifetime": 3600000, "maxConnectionPoolSize": 100, "connectionAcquisitionTimeout": 60000 }, "_pool": { "_maxSize": 100, "_acquisitionTimeout": 60000, "_pools": {}, "_acquireRequests": {}, "_activeResourceCounts": {} }, "_connectionProvider": null, "_onCompleted": null }`

Now, when I try to run a simple query, I get this error in the Developer Tools console:

`index.js?cb56:1155 WebSocket connection to 'wss://localhost:7687/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`

`Uncaught (in promise) Error: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3`

**Comment by lauri108** [comment]
Adding that after connecting, this.$neo4js.getSession() returns

`{ "_mode": "WRITE", "_readConnectionHolder": { "_mode": "READ", "_connectionProvider": { "_address": "localhost:7687", "_connectionPool": { "_maxSize": 100, "_acquisitionTimeout": 60000, "_pools": {}, "_acquireRequests": {}, "_activeResourceCounts": {} } }, "_referenceCount": 0, "_connectionPromise": {} }, "_writeConnectionHolder": { "_mode": "WRITE", "_connectionProvider": { "_address": "localhost:7687", "_connectionPool": { "_maxSize": 100, "_acquisitionTimeout": 60000, "_pools": {}, "_acquireRequests": {}, "_activeResourceCounts": {} } }, "_referenceCount": 0, "_connectionPromise": {} }, "_open": true, "_hasTx": false, "_lastBookmark": { "_values": [], "_maxValue": null }, "_transactionExecutor": { "_maxRetryTimeMs": 30000, "_initialRetryDelayMs": 1000, "_multiplier": 2, "_jitterFactor": 0.2, "_inFlightTimeoutIds": [] } }`

So, by the looks, I'm able to establish a session as well? But then, running the query (which is a simple COUNT(n) that works in the desktop browser without issues) results in the above error.

I'm using Chrome for my web app testing, if that makes a difference.

**Comment by wirespeed43** [comment]
`export default {
  data() {
    return {
      protocol: 'bolt',
      host: 'localhost',
      port: 7687,
      username: 'neo4j',
      password: 'password',
      encrypted: false    // add this
    }
  }
}`

**Comment by cherymann** [comment]
Hey @lauri108 ,

pass encrypted=false as a variable to neo4j.connect
