### ISSUE TITLE
this.$neo4j is undefined

### ISSUE THREAD

**Issue by sebastianjung** [adam-cowley/vue-neo4j#6]
What i did:
- create nuxt app with spa mode
- `npm i vue-neo4j`
- add a plugin in nuxt.config.js with contents like so:
```
import Vue from 'Vue'
import VueNeo4j from 'vue-neo4j'

Vue.use(VueNeo4j)
```
- copy code from example in vue-neo4j readme file and put it inside a component
- click the connect button leads to:
`Cannot read property 'connect' of undefined`

Any ideas what's happening? I didn't have trouble adding plugins like this before.

**Comment by adam-cowley** [comment]
What was the command that you ran to create the nuxt app?  Do you have the version numbers of vue/vue cli?

If you could point me towards a repo with the issue that would be really useful

**Comment by sebastianjung** [comment]
I'm sorry but i decided to go against connecting to a db on the frontend for security reasons :/

But thanks for coming back at me so quickly!

**Comment by adam-cowley** [comment]
Good idea!  I'd still like to get this fixed for the next person if you could provide some more info.
